# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CD with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository access
      uses: actions/checkout@v2 # Check if the workflow can access our repo
    
    - name: Set up Java 11 environment
      uses: actions/setup-java@v1 # Sets up a Java environment
      with:
        java-version: 11
       
    - name: Build with Maven
      run: mvn -B package --file pom.xml
