# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout repository access
      uses: actions/checkout@v2 # Check if the workflow can access our repo
    
    - name: Set up Java 11 environment
      uses: actions/setup-java@v1 # Sets up a Java environment
      with:
        java-version: 11
       
    - name: Test with Maven
      run: mvn test

  build:
    if: ${{ github.ref == 'master' }}
    needs: test
    runs-on: self-hosted
    steps:
    - name: Build with Maven
      run: mvn -B package --file pom.xml
     
  deploy:
    if: ${{ github.ref == 'master' }}
    needs: build
    runs-on: self-hosted
    steps:
    - name: Deploy with Maven
      run: nohup mvn spring-boot:run &
