# Workflow of JEE-Server

name: CI/CD

on:
  push:
    paths-ignore:
      - '.github/**'
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository access
        uses: actions/checkout@v2 # Check if the workflow can access our repo

      - name: Set up Java 11 environment
        uses: actions/setup-java@v1 # Sets up a Java environment
        with:
          java-version: 11

      - name: Test with Maven
        run: mvn test

  build-dev:
    if: github.ref == 'develop' && github.event_name == 'push'
    needs: test
    runs-on: self-hosted
    steps:
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build . --tag jee-serve:dev

  publish-dev-image:
    needs: build-dev
    runs-on: self-hosted
    steps:
      - name: Log-in on Docker repository
        env:
          DOCKERIO_USERNAME: ${{ secrets.DOCKERIO_USERNAME }}
          DOCKERIO_PASSWORD: ${{ secrets.DOCKERIO_PASSWORD }}  
        run: |
          docker login -u "$DOCKERIO_USERNAME" -p "$DOCKERIO_PASSWORD"

      - name: Tag of the new image
        run: docker tag jee-server:dev alexandrebis/4al2-jee-project:lastversion-dev

      - name: Push of the new image
        run: docker push alexandrebis/4al2-jee-project:lastversion-dev

  deploy-dev:
    needs: build-dev
    runs-on: self-hosted
    steps:
      - name: Stop previous Docker image
        run: docker rm jee-server || echo "Server already stopped"

      - name: Launch new Docker image
        run: docker run -d -p 8080:8080 --name "jee-server" jee-server

  build-prod:
    if: github.ref == 'master' && github.event_name == 'push'
    needs: test
    runs-on: self-hosted
    steps:
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build . --tag jee-server:prod

  publish-prod-image:
    needs: build-prod
    runs-on: self-hosted
    steps:
      - name: Log-in on Docker repository
        env:
          DOCKERIO_USERNAME: ${{ secrets.DOCKERIO_USERNAME }}
          DOCKERIO_PASSWORD: ${{ secrets.DOCKERIO_PASSWORD }}
        run: |
          docker login -u "$DOCKERIO_USERNAME" -p "$DOCKERIO_PASSWORD"

      - name: Tag of the new image
        run: docker tag jee-server:prod alexandrebis/4al2-jee-project:lastversion-prod

      - name: Push of the new image
        run: docker push alexandrebis/4al2-jee-project:lastversion-prod

  deploy-prod:
    needs: [build-prod, publish-prod-image]
    runs-on: self-hosted
    steps: 
      - name: TODO
        run: echo "TODO Deploy the image to Beanstalk"
